import java.util.HashMap;
import java.util.Map;

public class TTyyyy {


    static String ssss = "xuynrwsjaxzwmhktdayzzoxbbemejgosgcynfapykbcnzhesvnctfvdspqkuyrjhykpadahbhjbatvsxlngbtxmqrbwqromfqzyabzrcoorbbyklndcqdjzcnsmgmwmpbgjqoykrvnafhqrwfajnfahyqocdbgfnlaozmffvvmoymbmytjvfcgttcijyyljdgwjbztlpswmalgbgpaplqgzqchflxtypttkrpfvxrtkzpzrscwbxqbwfqqvjcukjbsginxqmxryxieyavnzdiludhthpreyelgcnpsoqswsreogbmveofvusdsxcjvdrjkhxkqrqzjbrpljwuzplxczqeevvbvcwhnvzuszqvhlmaptylyufqzyldwwgezlqurzvorxwgdtgjilgydqvpkntwjbgihlwckorgrmxixylxjmlfvhbpoaboylcedyzeayigfagitkrextlipvqqhdmoerchoqxbypihdvpdtjrrkxroowtrexuhucxpiibvmuyarjwqpcoywawqwdmfpwvamisnskbhopoqdsrefjtmnmvkyccremktrniqwoofoeenbzvvlrfcsftapyujmwdupdqikocrdyexjbcxwqeaumqoklsqebuzeziiswzfzgyhvnwjcnshdybjywyaodsywmlmuueocfruntpztlbggsuzctocyilfzpszgrgjsimqypqopfumpmsjvmsbrcfwretbiekoxpmplpcgewmqigymreqevdydvgmuyytguexnycqhwialkbjgzcklmgxgijjyjlplrsxznfkoklxlvpxrbasbznvxasxztwnqbhqultkyfqxsaeqztxbuwpzdpkngnuoayckfykdlarmuwprgtghfxfbgpucqwbihemixqmypjedyedimaanpbdrxpvtoxmxzimgfaouzlteobnadoshnxnufgmypupeikfqrqyexoljhqsaneicvaerqxcngmsidszagpiuiiasrezakiuroadojxmvgqgdodwwjszyeruwnupqgmyrjxigaskpjmzpsbhgokwtfcisjzvepyebwrcpafxzhbdgjykhzemfomgxjphcscuxjnywoiwbdvusywqlsccvsropvrnxtmkgiwfvqfkotpdznjinpobubzbvstkkvubuucilxyhjbcilfldibmyebrlcnvnuuqfvhwxoorbyyiigppuftqswpksfdxicemjbftgoabwrqdoudfbyjutkeqakoarruhwuznnlydivfelxvtggkkkjmxlwbkbklbwfsvrbadvraqovanlsmklnfjxxvzdjlpyurxpjcssebtpznwoytjefobdynaiukctgrzjxzirzosjuncvhfhcnhhrajahitnbkvwtifcoqepqyzwyazzkddxywvgqxofsyxngevsdbatvzmziqpmjewiyorpzsupxoflqpbyzhtvvpjdcqnlvlzrzakvmxzbaeipmwouvpvgtekfkuajjogbxhjiiqisdbplotyakxjvkmxhtmyznhaylqjnqzrwrmgtumbbhflizbpeohsufreefajrcsfoghglucidbnlysamvyatutjdfnvhahxykurbrmmadeaxhghvfacnjxqjathltizloasimpzugutrjfozvgmdakdhaofiephsnuztnpqhdlfrfuyprcrcszmgplszwfndzihegtbxbspaucjbmsamjyqqraszaghzlgnfoasvljxltcnumquohlcgtfjmrmfccjrhfedlievtpieworwhyiucsetdtuquartspkotmxqpnkeluekveljyugrloqczljmwtmfkyvqguqquztpjidglpxqfxvhlftvvimvrozdyywopwyfovdzopwlumocnyuoumehvjqpzkcfcgihicdrdtttiixlhpikbvjgoblttgvmndkqggypgwsibcqahmyyeagklprtvojuwlcblwidhjpugkbuspeynaoocgkzrpcnbqajopjjlfthevbculqsozkndgojnjnxqsoqiazyesldujjlpeedrswybwlfyzphixzluwbtmoxokksbedrqfuizopajzeahvalehdfnrkmnlpimduzgmwszcxmracvelbhjzmiwdnxwruqcugmkscfodjxghwcbmsokdspilajnibphjrvvlwpbojlpwuytkosjjojczwonovrxsiyuidphsklrmialvzpjcjtpblsgqljhuuvkcgpopdruidbaguevssjulnqgsixuhdhffrizkwtcbmrsrmtinefwxwwilbezedywxuitdzyypdgoveeupeusrgkqwfslfnjlybghedeabnrlzcgflgxiftmfzcsnybqcegpxtepyifqblzdjrtynxjgbiymhjumliovwnugaqebfewwkoidmaokmpfxhdemfdfupfzicfqswfeoabqhxacqtevyikwjehfdanujqafshypyewwjbffslrorfwenywrixohirymriuukgrrtvinivxjhxauswnxiwetklmaeooopzxwqedcmzqbsqcpizgbsnjvbavwkhswlmsigpcdcistimknaqvikbixsixlvpqtrudseizfbhedqqnekuuripcveufzesfmgamjqlwcasahdphjenjqpozqbrilknrrvuapnijdnjizdqjcjlmvnumtmfdacviecjhxszgjifdjjlyatxljwajusxelheahcqyochiwuhjxxkwtnxqxrnhuehggrumxyzfhptjoafloounyiwqjybrbpvdhqeicodbznxbvhwqcieohgwhrhyzmeadmdoyclrkawftecpyuxlktpfzbslhuembqldignaxzdunxfdoeouwbohtvgswqennprrhgvhydpcthgicuywqfsxzfrxkjzmfgzqmsmjlopwtccptklgttsgjpilmmanfgcnxwjasuztfcgspeuolfecspzicixskeohywefgyazogdhyzuqihushpflcgenuwpvomjjudthwpoahrmqzjxaffrqaogakovphsmjlaqzxkqidudvcizzlwtixsbqvbhhxplwaerwwzwpbjnkaptkbprrrkjfpwdqniqekyqtufnvmzsmiozswbcmjqhfnwyndzshjplypufjwxzzjeifnvinopyawcpbbarngbshrkkesrkqfdickjgzlcemkrxucnxpzwuiejkvvrvdiyjigkevirxqzdwtjyekogikuemljorbggakyubanivnepzmnrhxxchrcpmvzzmnlimilrztjglcorfnlodbtrcmxuwcoxtyehmrplyekiclziwuuewttooqfibpsnqhpatnqtccxdwwnqvhvyzgezymbkrayjkunmqubehhurllunmcqidudhhxdxqdcqzbvfzryjoyxrmnbbanqweywthlteowleciptekpdseykixytisrdyppihqajzovglupocoljegjnnmgomgmgklnurzckpowalwlahcnlubdrhffxhbisayrsnfegfiaphrymahhjtvsoimolphfayoykgsbwyaaclkplesjxbjazjndixcjkxuflasnaiukgifhgprnnxjmdwhuijkyzznlkjpzgupaijoiydjiblwqadpjqghvkbuestnkcpfjkzkqlgyaeeclyyjjphygrkkuswhvyzhkchnwjkkpjtlfboyfrjdrzjnjpyojnxxtjmbkigrdgcedgogntniteliduveerjytcdeapwwctktbldqdduhhpsrmxsrdoeqnulkrwmqsskatefqrewhjujhndtnzmbklrmzjunjfacgcgjkambcwdjsptrxqicurmmymlszebxvqvysatxjracsqxstpbqctwonggowblitkpajycmzojmwlhgscsqedhcvcnaabuynaoudqdxsesgclyqsyszgbuopswlommhrgwmcauxyrlthyzjpgqfzasrmvvsgmwbbahgxcbgjksyhsonzwbztpczvfwpklvnbymfvzcpjwlbsmqnhytqvgsyyvixbrxgrwwfrpoefylfxkvobpurwgwcrqbvaxartfqydhbzaxwevoxbajbaelvvmnkfhqueutymrfzptpzxmrnbcfbfvckhliqyfvukkmidllfvnkpyjbpuqyoxeptnvpspejfxqpxunklfsywrrxqjxsyqtqpjctbgfqacuvidrrupnwkxjqrkrikqsprqfrxiqdnmvajelgqbuxtjlvljqlpkhbdshjgwlklljlbbzxmamasxyoifehtipnqghutdnsmukooklcgkrlggujcpkdncrqxvabmteyuyanczczrxtjizmqhctipugwbtxbhvajtueaoobndevaksquwbxyqckiaokmjpcasofaebjdfwgjgfredchrykojbjyrhbjzgmauumsvojkbrltyfwnvzsjgsdhgtgjxpkrueoudvyvtnwkjkbyvyoiwlzifnbsyxyqsyzddmwuyvtyrzealoqymdpniarscwxopuyqiowyasywkayvmjfizjxqbagptfvtwevqhrgpfzrmelxfbjhwhjwkvgnidszswbthdroqwilidtvgfftdyqvyrsvzygspnfctvpkkxvnbvribvjlwcwarzbrwdntgrmacjkixtgovvlfabjormwbcqfqkujvooprfhossmiiezoqmrbmccgfdrpnrwqkdicgbgmyqylwfecmxvweliuxmjusvtmcvqmdovdbvdafuvbkzwlbnvvmcvlyrntomjvznyxzajelurdwugmxwxyoaqsshlmxwmrxtnlumtwhhtxhbdztrfzpsokzewfsjmfkrlwnalspxwglxbucslfhpbhkqkswrkwsthyoddznhfkcpjwrwjtgdlieakswwkkuymijlobycgcvefclgrtynobgitjrgxqmevjcphhkwyqebswsoezfuwmokmbcnzgddrihahtsoatofqjzgmhxulfnkspqiodrugrlhupctfbowtxujuxnthlojcxshhhsizipsinwofvahpccpvdtshtrtqfvjejhmwupvvpbyabxgvismpyjwqzvhabwbnciuidtolkiqxplqoxtrzejgalfkqagqinrkbpvpzfawvfejjqybdmqocdvckvdvwzwfgrxbfazyumodsinhhxzrtdhbscgqlagriuxclekcgmtpgalvnvwhatvtwmwbegcoaipnzccvzvkqwkcirntpvgafwmaycpyazvwupyvfwytlnirumssjkhynziplhbskmuxcwjwtmtytyqiegjtoxoodcwlfdwfmywyogoqnesckshxlzrrypogfjnnjtebschajqshavnpfkmhsuhzbcazxniqxtozyftjfwbtnqriahgdvbzgtmnfajvqimnkfhpenhifnzyejolnpuhjekciyspithxccgtcukyfxsenkhhfkdhpsvwqenxpqsrvplpuujdzzqixebkfgzdwwumrpqqnbfqrsehueortxlrqeekuqdnitsfsqqygrszkqcrmqzoqgixlaflsrqrfumbajpadutukaiutomcacuoptrbaizyvlvqgyqkxesbruvegcjojvibdwnygkvrgtwrjxhaxrscyfygjvwpywglqkwjdgyudhcylydoqicocqihmiqfuzanbosdymozegktmzikewzajbenojjjavawlcgqnncarcdulstdgdgkqvywkobmtlnksjnnnwjxjqbgvtfpdrbywxjbjccgunesgfwnqjpsqpypvyejppnlanbrvczcxnjulnqydggzuakjzucbxzzvrjqhquvmxzwqepmwmnzmiqovnwzmuswmhjhkveorpleeablhdxpxxdchbjqygmfkfcrkbyhdjtaqarcduroifprjdphxnxjzbsjzsfzjwyehqclsdhsfbcbdhohmvdgxadqqpkzarjinwlahclwqmbvyffnbezamaxqzmbvkpoxjdnpxnaomoxbjgifknhwuldgrktjdfilzhxizwcorcpqezfuewcdzrrukwvfdzornrnvmxgmhwlwjeyjvdhpicbbmrhkebkhgwzqbzkxtcprfqxwcpuoccnznjubetfbtwtqphniqicrhqjjuxmcjqzwdmqdyzlkozknlljnjvlwtkbuacwrouefjavagljzfmqzbarxopxexkjrtvoicsfffofgbhzdicxfigvkqoorzmqegpscwyrpxwtswbwleokbkwajcqnuabrwqrrhpprlqgfjucrnedpueqkngjslhpcyjhilxooydtjacbwdvrkztkegripukgdtagwpbudqnojzysdnqebynlmszgrremcnhnrdujasvawepukevrftatrqyxgvxbxxcmgvqhuilkxjsbjuuekopspgiocnizihudgvuqnesssdmzzizhthxejwkvudzsiccbwbohbqqixmfmjdmpknkmpxtmhwiegkgcvxeavctlebngffcnfmimxsmrvubwoacbdnxvylvremlsqygmvwypcszafolbqtcxvyhcadmraetgafitxbpzaggdspkyiszcaybkncldgicukjlxdrfzdypyjuzhlxsdrccgmrhkgtfrmrzwklplfntsjjhycmiyzozprsszulgztynaeyrsvltzlkgjmlrqgkwjwwojilkvtxpywabilteyiecgtxohfsuxvuynlxmuckakouowomlbbfbojgzihemqihtkddqudqowongfpvddlgbnggobllywazbhhjrrmadcjhrizzkvnthptoxlavjneevoadaledxwjezpbuxncjzvfmjkqywixrwmzuqpegtesweamgrudavborznlkcycghlbnpgzlwyetdnskcipiwwmceppqdpdwucqqivhkrkiobqjmzcxnfztpxsimbooizjutynrqwkguhccmvqdurpcdczvsnbvkdpbbepnvospsesmtpzmuwapyuslhviacdjqpeulhamrkgtvpulqozyhwnjvltllbozbarskmvzsurgkonyhtfluemczalfetsnyywqznewushquctpuwwsssmytxktxlnqfpwbqehjuzjhczkkmigqboyfhqssloxmqrkkqzxtvfbtjdnrqcsydjiqvejmpnaggbntxutqgyexlufpjfhymxxaimbviwcoqfthnkreesgfrsocwkbwhvggcbkbpsgnbbyoxcnrrtarjtjelnlzpdgjmdocnovnnonpzyliwrqhfwggnglvpiebomxhbhrxryweeheuxzztgyvbeirpdplqukvghobiidqyrkhokgbsetctgldhxdpthorvykangmukdvwarspczynpbhrplmgnqjkddtbwwabyzkdwacsccrjpiidqixljpnzxaklqbtpensdnlkckqiktdxkjbwvqafimtgyhsjsugesetxxktwulvixzcvgbsesvnniypjftjafdtijwhiszdjjmsmncrhdrnnrxaaedkidilykmnocijznujobhkdssbemhlghgszmshajqixnnvsnrfiltfsquhdwohykvwcaekybzaipgjpwtssywhmdczdopllcjyqcyrgsrwiwveyigrneoqzewviwyvcrhsflzkzqkcwlmjqahbhrlglbynwefzugayonnvhgjsjmykpwvmfvljboxyivpnizktocxegnvipwgoexoudqfflmksmqrgdcxwzeqqvmszevqghihwbqjwausohbttbmczigkrelnzpckfvvxmywvhmarohwzgceukiecrvbiwzrnpduggshophdkczyngpzhpzjijamkcivuwtffdhmmdqdaqgdmtdcjmboylnybykkbpgsxvhghwscwocufdjfyypqjuwwwnhyespqvtmosbzagibikldlxqfmcodegkfyppjgkgonvugnsnblngdhpgelwimckpfqoliqvfaxxlnqcjqkzhkpvfuwqnwqnyrvhpzorngbafy";
    static int minlen = 11;
    static int maxlen = 24;
    static int maxUni= 2;

    public static void main(String[] args) {
        getMaxOccurrences("ababab", minlen, maxlen,maxUni);
    }


    public static int getMaxOccurrences(String components, int minLength, int maxLength, int maxUnique) {

        int ans = 0;
        String s = components;
        Map<String, Integer> cnt = new HashMap<>();
        for(int i =0; i < s.length()-minLength+1 ;i++){

            String t = s.substring(i, i+minLength);
            Map<Character, Integer> ss = new HashMap<>();
            for(int j =0; j<minLength; j++){
                ss.putIfAbsent(t.charAt(j), 0);
                ss.put(t.charAt(j), ss.get(t.charAt(j)));


            }

            for(Character c : ss.keySet()){
                if(ss.get(c)> maxUnique){
                    ss.remove(c);
                }
            }
            if(ss.size()<= maxLength  ){
                // cnt.putIfAbsent(t, 0);
                cnt.put(t, cnt.getOrDefault(t,0)+1);
                ans = Math.max(ans, cnt.get(t));
            }

        }
        System.out.println(ans);
        return ans;


    }
}
